version: '2'

services:
     ray:
    image: hulisang/v2ray_v3:go_pay
    restart: always
    network_mode: "host"
    environment:
      sspanel_url: "https://go.sswiwi.com"
      key: "SalemWebapi"
      speedtest: 6
      node_id: 0
      api_port: 2333
      downWithPanel: 0
      LDNS: "localhost"
      TZ: "Asia/Shanghai"
      MYSQLHOST: ""
      MYSQLDBNAME: ""
      MYSQLUSR: ""
      MYSQLPASSWD: ""
      MYSQLPORT: 3306
      PANELTYPE: 0
      usemysql: 0
      CF_Key: ""
      CF_Email: ""
      MUREGEX: "%suffix"
      MUSUFFIX: "bing.com"
      ProxyTCP: 0  
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: hulisang/v2ray_v3:caddy
    restart: always
    environment:
      - ACME_AGREE=true
#      if u want to use cloudflare (for DNS challenge authentication)
#      - CLOUDFLARE_EMAIL=xxxxxx@out.look.com
#      - CLOUDFLARE_API_KEY=xxxxxxx
      - V2RAY_DOMAIN=xxxx.com
      - V2RAY_PATH=/ray
      - V2RAY_EMAIL=lusalem@yandex.com
      - V2RAY_PORT=10550
      - V2RAY_OUTSIDE_PORT=443
      - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - /etc/localtime:/etc/localtime:ro
